# Generated by Django 5.0.3 on 2024-03-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ['price']},
        ),
    ]
